services:
  BT_SERVICE_NAME6:
    image: zedeus/nitter:latest
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8080
    volumes:
      - ${APP_PATH}/config/nitter.conf:/src/nitter.conf
      - ${APP_PATH}/config/sessions.jsonl:/src/sessions.jsonl
    depends_on:
      - nitter-redis
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

  nitter-redis:
    image: redis:6-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ${APP_PATH}/redis:/data
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
